services:
  - type: web
    name: beverage-store
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd project && gunicorn beverage_store.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
